### ISSUE TITLE
Code for using CLIP-ViL as base model

### ISSUE THREAD

**Issue by xiaoying-xing** [facebookresearch/selective-vqa_ood#1]
Thank the authors for sharing this inspiring work! Could you please also upload the code and scripts for using CLIP-ViL as base model to reproduce some results in Table 1? Many thanks.

**Comment by SpencerWhitehead** [comment]
Hello,

Thanks for your interest! For the CLIP-ViL experiments, we used the open source implementation provided by [Whitehead et al. (2022)](https://github.com/facebookresearch/reliable_vqa). Appendix D.1.2 in our paper also has some additional info regarding the setup.

Hope this helps!
